/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kontaktlista;

import java.util.ArrayList;

/**
 *
 * @author jarhar
 */
public class KontaktJPanel extends javax.swing.JPanel {

    private KonManager konmgr = new KonManager();
    private FileManager filemgr = new FileManager();
    //private final Databas db = new Databas();

    /**
     * Creates new form KontaktJPanel
     */
    public KontaktJPanel() {
        initComponents();
        this.lblError.setVisible(false);
        if (this.rbtFörnamn.isEnabled()) {
            this.skrivUtFirstName();
        } else {
            this.skrivUtLastName();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txfFörnamn = new javax.swing.JTextField();
        txfEfternamn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfTele = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaKontaktArea = new javax.swing.JTextArea();
        btnAddKontakt = new javax.swing.JButton();
        rbtFörnamn = new javax.swing.JRadioButton();
        rbtEfternamn = new javax.swing.JRadioButton();
        lblError = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();

        jLabel1.setText("Förnamn");

        txfFörnamn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfFörnamnFocusGained(evt);
            }
        });

        txfEfternamn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfEfternamnFocusGained(evt);
            }
        });

        jLabel2.setText("Efternamn");

        txfTele.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfTeleFocusGained(evt);
            }
        });

        jLabel3.setText("Telefon");

        txaKontaktArea.setEditable(false);
        txaKontaktArea.setColumns(20);
        txaKontaktArea.setRows(5);
        txaKontaktArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txaKontaktArea.setEnabled(false);
        jScrollPane1.setViewportView(txaKontaktArea);

        btnAddKontakt.setText("Lägg till");
        btnAddKontakt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKontaktActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtFörnamn);
        rbtFörnamn.setSelected(true);
        rbtFörnamn.setText("Förnamn först");
        rbtFörnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFörnamnActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtEfternamn);
        rbtEfternamn.setText("Efternamn först");
        rbtEfternamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEfternamnActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setText("Fyll i alla fält.");

        btnSave.setText("Spara");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnLoad.setText("Hämta");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(rbtFörnamn)
                        .addGap(18, 18, 18)
                        .addComponent(rbtEfternamn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfTele, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddKontakt)))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLoad)
                                    .addComponent(btnSave)))
                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnAddKontakt)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtFörnamn)
                    .addComponent(rbtEfternamn))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKontaktActionPerformed
        String fNamn = this.txfFörnamn.getText();
        String eNamn = this.txfEfternamn.getText();
        String tele = this.txfTele.getText();

        this.lblError.setText("");

        if (!fNamn.trim().isEmpty()
                && !eNamn.trim().isEmpty()
                && !tele.trim().isEmpty()) {
            this.lblError.setVisible(false);
            this.txfEfternamn.setText("");
            this.txfFörnamn.setText("");
            this.txfTele.setText("");
            Kontakt kon = new Kontakt(fNamn, eNamn, tele);
            konmgr.addKontakt(kon);

            if (this.rbtFörnamn.isSelected()) {
                this.skrivUtFirstName();
            } else {
                this.skrivUtLastName();
            }
        } else {
            this.lblError.setText("Fyll i alla fält.");
            this.lblError.setVisible(true);
        }
    }//GEN-LAST:event_btnAddKontaktActionPerformed

    private void rbtFörnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFörnamnActionPerformed
        this.skrivUtFirstName();
    }//GEN-LAST:event_rbtFörnamnActionPerformed

    private void rbtEfternamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEfternamnActionPerformed
        this.skrivUtLastName();
    }//GEN-LAST:event_rbtEfternamnActionPerformed

    private void txfFörnamnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfFörnamnFocusGained
        this.lblError.setVisible(false);
    }//GEN-LAST:event_txfFörnamnFocusGained

    private void txfEfternamnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfEfternamnFocusGained
        this.lblError.setVisible(false);
    }//GEN-LAST:event_txfEfternamnFocusGained

    private void txfTeleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfTeleFocusGained
        this.lblError.setVisible(false);
    }//GEN-LAST:event_txfTeleFocusGained

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        filemgr.saveToFile(konmgr.getLista());

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        ArrayList<Kontakt> kon = filemgr.readFromFile();
        konmgr.createNewList(kon);
        if (this.rbtFörnamn.isSelected()) {
            this.skrivUtFirstName();
        } else {
            this.skrivUtLastName();
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void skrivUtFirstName() {
        this.txaKontaktArea.setText("");
        ArrayList<Kontakt> lista = konmgr.getLista();
        for (int i = 0; i < lista.size(); i++) {
            Kontakt kon = lista.get(i);
            this.txaKontaktArea.append(kon.getFörnamn() + "\t"
                    + kon.getEfternamn() + "\t"
                    + kon.getTelefon() + "\n");
        }
    }

    private void skrivUtLastName() {
        ArrayList<Kontakt> lista = konmgr.getLista();
        this.txaKontaktArea.setText("");
        for (int i = 0; i < lista.size(); i++) {
            Kontakt kon = lista.get(i);
            this.txaKontaktArea.append(kon.getEfternamn() + "\t"
                    + kon.getFörnamn() + "\t"
                    + kon.getTelefon() + "\n");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddKontakt;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JRadioButton rbtEfternamn;
    private javax.swing.JRadioButton rbtFörnamn;
    private javax.swing.JTextArea txaKontaktArea;
    private javax.swing.JTextField txfEfternamn;
    private javax.swing.JTextField txfFörnamn;
    private javax.swing.JTextField txfTele;
    // End of variables declaration//GEN-END:variables

}
